version: '2.1'
services:
  dockerhub:
    restart: "always"
    image: cintiadr/dockerhub-webhook
    ports:
      - "3000:3000"
    environment:
      SERVER_PORT: 3000
      TOKEN: ${TOKEN:-abc123}
      CALLBACK_DISABLE: 'true'
    volumes:
      - ./scripts:/src/scripts
      - /root/docker:/root/docker
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: "wget -O /dev/null localhost:3000"
      timeout: 20s
