---
# Add users/groups/ssh keys
- name: Create user groups
  group: name="{{item.key}}" 
         {% if item.value.uid is defined %}
         "gid={{item.value.uid}}"
         {% endif %}
  with_dict: users
  tags: ['users','groups']

- name: Create other groups
  group: name="{{item.key}}" gid="{{item.value.gid}}"
  with_dict: othergroups
  tags: ['users','groups']
  when: othergroups is defined


- name: Create users
  user: name="{{item.key}}"
        group="{{item.key}}"
        groups="{{item.value.groups | join(',')}}"
        shell={{item.value.shell if item.value.shell is defined else users_default_shell}}
        comment="{{item.value.name}}"
        {% if item.value.uid is defined %}
        "uid={{item.value.uid}}"
        {% endif %}
        createhome="yes"
        state=present
  with_dict: users
  tags: ['users','groups']

- name: SSH Keys
  authorized_key: user="{{item.key}}" key="{{item.value.ssh_key}}"
  with_dict: users
  tags: ['users','ssh-key']

- name: Deleted user removal
  user: name="{{item}}" state=absent
  with_items: users_deleted
  when: users_deleted is defined
  tags: ['users']

- name: Deleted per-user group removal
  group: name="{{item}}" state=absent
  with_items: users_deleted
  when: users_deleted is defined
  tags: ['users','groups']
