---
# Add users/groups/ssh keys
- name: Create user groups
  group: name="{{item.key}}" 
         {% if item.value.uid is defined %}
          "gid={{item.value.uid}}"
         {% endif %}
  with_dict: users
  tags: ['users','groups']

- name: Create other groups
  group: name="{{item.key}}" gid="{{item.value.gid}}"
  with_dict: othergroups
  tags: ['users','groups']
  when: othergroups is defined


- name: Create users
  user: name="{{item.key}}"
        {% if users_default_create_user_group %}
         "group={{item.key}}"
        {% endif %}
        groups="{{item.value.groups | join(',')}}"
         shell={{item.value.shell if item.value.shell is defined else users_default_shell}}
        {% if item.value.name is defined %}
         "comment={{item.value.comment}}"
        {% endif %}
        {% if item.value.uid is defined %}
         "uid={{item.value.uid}}"
        {% endif %}
         createhome={{item.value.createhome if item.value.createhome is defined else users_default_createhome}}
        {% if item.value.generate_ssh_key is defined %}
         "generate_ssh_key={{item.value.generate_ssh_key}}"
        {% endif %}
        {% if item.value.home is defined %}
         "home={{item.value.home}}"
        {% endif %}
        {% if item.value.password is defined %}
         "password={{item.value.password}}"
        {% endif %}
        {% if item.value.ssh_key_bits is defined %}
         "ssh_key_bits={{item.value.ssh_key_bits}}"
        {% endif %}
        state=present
  with_dict: users
  tags: ['users','groups']

- name: SSH Keys
  authorized_key: user="{{item.key}}" key="{{item.value.ssh_key}}"
  with_dict: users
  tags: ['users','ssh-key']

- name: Deleted user removal
  user: name="{{item}}" state=absent
  with_items: users_deleted
  when: users_deleted is defined
  tags: ['users']

- name: Deleted per-user group removal
  group: name="{{item}}" state=absent
  with_items: users_deleted
  when: users_deleted is defined
  tags: ['users','groups']
