---
# Add users/groups/ssh keys
- name: Create user groups
  group: name="{{item.username}}" gid="{{item.uid}}"
  with_items: users
  tags: ['users','groups']

- name: Create other groups
  group: name="{{item.groupname}}" gid="{{item.gid}}"
  with_items: othergroups
  tags: ['users','groups']


- name: Create users
  user: name="{{item.username}}"
        group="{{item.username}}"
        groups="{{item.groups | join(',')}}"
        shell={{item.shell if item.shell is defined else users_default_shell}}
        comment="{{item.name}}"
        uid="{{item.uid}}"
        createhome="yes"
  with_items: users
  tags: ['users','groups']

- name: SSH Keys
  authorized_key: user="{{item.0.username}}" key="{{item.1}}"
  with_subelements:
    - users
    - ssh_key
  tags: ['users','ssh-key']
