---
# Add users/groups/ssh keys
- name: Create user groups
  group: name="{{item.username}}" 
         {% if item.uid is defined %}
         "gid={{item.uid}}"
         {% endif %}
  with_items: users
  tags: ['users','groups']

- name: Create other groups
  group: name="{{item.groupname}}" gid="{{item.gid}}"
  with_items: othergroups
  tags: ['users','groups']


- name: Create users
  user: name="{{item.username}}"
        group="{{item.username}}"
        groups="{{item.groups | join(',')}}"
        shell={{item.shell if item.shell is defined else users_default_shell}}
        comment="{{item.name}}"
        {% if item.uid is defined %}
        "uid={{item.uid}}"
        {% endif %}
        createhome="yes"
  with_items: users
  tags: ['users','groups']

- name: SSH Keys
  authorized_key: user="{{item.0.username}}" key="{{item.1}}"
  with_subelements:
    - users
    - ssh_key
  tags: ['users','ssh-key']

- name: Deleted user removal
  user: name="{{item.username}}" state=absent
  with_items: users_deleted
  when: users_deleted is defined
  tags: ['users']

- name: Deleted per-user group removal
  group: name="{{item.username}}" state=absent
  with_items: users_deleted
  when: users_deleted is defined
  tags: ['users','groups']
