---
  - name: 'Delete old puppet files'
    file:
      name: "/etc/puppet"
      state: absent
  - name: Copy puppet files
    copy:
      owner: 'root'
      group: 'root'
      mode: 0700
      src: ../bamboo-agents-puppet/
      dest: /etc/puppet
  - name: Bootstrap puppet ( it can take a long time - logs in /var/log/puppet-bootstrap.log)
    shell: bash /etc/puppet/bin/first-boot.sh | tee /var/log/puppet-bootstrap.log
  - name: Run puppet ( it can take a long time - logs in /var/log/puppet-runs.log)
    shell: bash /etc/puppet/bin/run-puppet.sh | tee /var/log/puppet-runs.log
    register: puppet_output
  # - name: Print puppet output
  #   debug: var=puppet_output.stdout
