---
  - name: Remove previous puppet clone
    file:
      name: "puppet"
      state: absent
  - name: clone puppet repository
    shell: GIT_SSH_COMMAND='ssh -i /root/.ssh/github_id_rsa' git clone --depth 1 git@github.com:openmrs/openmrs-contrib-itsmresources.git puppet
  - name: Remove previous puppet folder
    file:
      name: "/etc/puppet"
      state: absent
  - name: Recreate puppet folder
    shell: mv puppet/bamboo-agents-puppet /etc/puppet
  - name: Bootstrap puppet ( it can take a long time - logs in /var/log/puppet-bootstrap.log)
    shell: bash /etc/puppet/bin/first-boot.sh | tee /var/log/puppet-bootstrap.log
  - name: Run puppet ( it can take a long time - logs in /var/log/puppet-runs.log)
    shell: bash /etc/puppet/bin/run-puppet.sh | tee /var/log/puppet-runs.log
    register: puppet_output
  # - name: Print puppet output
  #   debug: var=puppet_output.stdout
