---
  - name: add executable mode to deploy script wrapper
    file:
      state: 'directory'
      path: "/etc/nginx/ssl"
      mode: "0755"

  # https://workshop.avatarnewyork.com/project/datadog-ssl-expires-check/
  - name: Allow cert access to datadog - archive
    file:
      state: 'directory'
      path: "/etc/letsencrypt/archive"
      mode: "0711"
  - name: Allow cert access to datadog - live
    file:
      state: 'directory'
      path: "/etc/letsencrypt/live"
      mode: "0711"
  - name: Allow cert access to datadog - hostname
    file:
      state: 'directory'
      path: "/etc/letsencrypt/live/{{ inventory_hostname }}"
      mode: "0755"
  - name: Ansible copy files remote to remote
    copy:
      src: files/ssl_check_expire_days.py
      dest: /opt/datadog-agent/agent/checks.d

  - name: Check if datadog-agent was restarted yet
    command: dd-agent info
    register: datadog_restarted
    changed_when: datadog_restarted.stdout.find('ssl_check_expire_days') == -1
  - name: Restart datadog-agent service
    shell: systemctl restart datadog-agent
    when: datadog_restarted.stdout.find('ssl_check_expire_days') == -1
