---
# - name: Creates docker compose directory
#   file: path=/root/{{docker_deployment}} state=directory

- name: copy docker compose files
  copy: src="{{ role_path }}/files/{{item}}" dest="/root/docker"
  register: docker_compose_projects
  with_items:
    - "{{docker_deployment}}"
  notify:
    - restart docker compose


- include: autodeploy.yaml
