---
# Master Playbook
- hosts: all
  roles:
   - users
   - sudo
   - sshd
   - ufw
#   - timezone
#   - ntp
#   - ssl-keys

- hosts: mysql
  roles:
   - mysql

- hosts: www
  roles:
   - ssl-keys

- hosts: bamboo-agent
  roles:
   - crontab
