---
# Master Playbook

# TODO: include this task to all hosts
# should happen before installing datadog
- hosts: web
  become: true
  tasks:
   - include: tasks/hostname.yml

- hosts: all
  become: true
  tags:
    - base
  roles:
   - users
   - sudo
   - sshd
   - ufw
   - datadog

- hosts: web-tls
  become: true
  tasks:
    - include: tasks/nginx-hacks.yml
  roles:
    - dhparam
    - letsencrypt

- hosts: web
  become: true
  roles:
   - nginx

- hosts: backup
  become: true
  tags:
   - backup
  tasks:
   - include: tasks/backup.yml
  roles:
   - aws-cli

- hosts: bamboo
  roles:
   - timezone
  vars:
   timezone: UTC

- hosts: docker
  become: true
  tags:
    - docker
  roles:
   - docker
   - docker-compose
   - docker-compose-openmrs
  tasks:
   - include: tasks/docker-install-hacks.yml

- hosts: ldap
  become: true
  tasks:
    - name: Insert ldap backup
      copy:
        owner: root
        group: root
        mode: 0700
        src: ../scripts/ldap-backup.sh
        dest: /opt/scripts/ldap-backup.sh
      tags: backup

- hosts: mongodb
  become: true
  tasks:
    - name: Insert MongoDB backup
      copy:
        owner: root
        group: root
        mode: 0700
        src: ../scripts/mongo-backup.sh
        dest: /opt/scripts/mongo-backup.sh
      tags: backup
