---
# Master Playbook
- hosts: all
  become: true
  roles:
   - users
   - sudo
   - sshd
   - ufw
   - datadog

- hosts: web-tls
  become: true
  tasks:
    - include: tasks/nginx-hacks.yml
  roles:
    - letsencrypt

- hosts: web
  become: true
  roles:
   - nginx
  tasks:
    - include: tasks/hostname.yml

- hosts: bamboo
  roles:
   - timezone
  vars:
   timezone: UTC

- hosts: docker
  become: true
  roles:
   - docker
   - docker-compose
   - docker-compose-openmrs
  tasks:
   - include: tasks/docker-install-hacks.yml


# TODO: make a role
- hosts: ldap
  become: true
  tasks:
    - name: Insert ldap backup
      copy:
        owner: root
        group: root
        mode: 0700
        src: ../scripts/ldap-backup.sh
        dest: /opt/scripts/ldap-backup.sh
      tags:
        - backup
