---
# Master Playbook

# TODO: include this task to all hosts
# should happen before installing datadog
- hosts: web
  become: true
  tasks:
   - include: tasks/hostname.yml

- hosts: all
  become: true
  tags:
    - soe
  roles:
   - users
   - sudo
   - sshd
   - ufw
   - datadog
  tasks:
    - include: tasks/extra-monitoring.yml

- hosts: web-tls
  become: true
  tasks:
    - include: tasks/nginx-hacks.yml
  roles:
    - dhparam
    - letsencrypt

- hosts: web
  become: true
  roles:
   - nginx

- hosts: backup
  become: true
  tags:
   - backup
  tasks:
   - include: tasks/backup.yml
  roles:
   - aws-cli

- hosts: bamboo
  roles:
   - timezone
  vars:
   timezone: UTC

- hosts: docker
  become: true
  tags:
    - docker
  roles:
   - docker
   - docker-compose
   - docker-compose-openmrs
  tasks:
   - include: tasks/docker-install-hacks.yml

- hosts: ldap
  become: true
  tasks:
    - name: Insert ldap backup script
      copy:
        owner: 'root'
        group: 'root'
        mode: 0700
        src: ../scripts/ldap-backup.sh
        dest: /opt/scripts/ldap-backup.sh
    - name: Insert LDAP database maintenance script
      copy:
        owner: 'root'
        group: 'root'
        mode: 0700
        src: ../scripts/ldap-maintenance.sh
        dest: /opt/scripts/ldap-maintenance.sh
    - name: Insert LDAP count utility script
      copy:
        owner: 'root'
        group: 'root'
        mode: 0700
        src: ../scripts/ldap-count.sh
        dest: /opt/scripts/ldap-count.sh

    - name: Cron jobs for LDAP Backup
      cron:
        name: 'backup ldap'
        user: root
        minute: "0"
        hour: "2"
        job: "/opt/scripts/ldap-maintenance.sh && /opt/scripts/ldap-backup.sh"
      tags: backup

- hosts: mongodb
  become: true
  tasks:
    - name: Insert MongoDB backup
      copy:
        owner: 'root'
        group: 'root'
        mode: 0700
        src: ../scripts/mongo-backup.sh
        dest: /opt/scripts/mongo-backup.sh
    - name: insert cronfile with MongoDB credentials
      template:
        owner: 'root'
        group: 'root'
        mode: 0700
        src: files/cronfile.j2
        dest: /root/.cronfile
    - name: Cron jobs for MongoDB Backup
      cron:
        name: 'backup mongo'
        user: root
        minute: "0"
        hour: "2"
        job: "/opt/scripts/mongo-backup.sh"
      tags: backup
