---
# Master Playbook
- hosts: all
  become: true
  roles:
   - users
   - sudo
   - sshd
   - ufw

#- hosts: mysql
#  roles:
#   - mysql

- hosts: www
  roles:
   - ssl-keys
  vars:
   ssl_key_loc: ~/omrs-cert/

- hosts: bamboo
  roles:
   - timezone
  vars:
   timezone: UTC

- hosts: docker
  become: true
  roles:
   - docker
   - docker-compose
  tasks:
   - name: Check if docker was restarted yet
     command: docker info
     register: docker_restarted
   - name: Restart docker service
     shell: systemctl restart docker
     when: docker_restarted.stdout.find('overlay2') == -1


# TODO: make own roles for this
- hosts: dbreset
  tasks:
   - name: Insert dbreset scripts
     synchronize: archive=no
                  dest=/opt/scripts/
                  mode=push
                  perms=yes
                  recursive=yes
                  src=../scripts/dbreset
