---
# Master Playbook
- hosts: all
  become: true
  roles:
   - users
   - sudo
   - sshd
   - ufw

#- hosts: mysql
#  roles:
#   - mysql

#- hosts: ssl
#  roles:
#   - ssl-keys
  #vars:
   #ssl_key_loc: ~/omrs-cert/

- hosts: web
  become: true
  roles:
   - nginx
  tasks:
   - hostname:
       name: "{{ inventory_hostname_short }}"
   - name: "Build hosts file"
     lineinfile:
       dest: /etc/hosts
       regexp: '^127\.0\.0\.1'
       line: "127.0.0.1 {{ inventory_hostname }} {{ inventory_hostname_short }} localhost"
       state: present

- hosts: bamboo
  roles:
   - timezone
  vars:
   timezone: UTC

- hosts: docker
  become: true
  roles:
   - docker
   - docker-compose
   - docker-compose-openmrs
  tasks: # https://github.com/andrewrothstein/ansible-docker/issues/8
   - name: Check if docker was restarted yet
     command: docker info
     register: docker_restarted
     changed_when: docker_restarted.stdout.find('overlay2') == -1
   - name: Restart docker service
     shell: systemctl restart docker
     when: docker_restarted.stdout.find('overlay2') == -1

# TODO: make own roles for this
- hosts: dbreset
  tasks:
   - name: Insert dbreset scripts
     synchronize: archive=no
                  dest=/opt/scripts/
                  mode=push
                  perms=yes
                  recursive=yes
                  src=../scripts/dbreset
