---
# Master Playbook
- hosts: all
  roles:
   - users
   - sudo
   - sshd
   - ufw
#   - timezone
#   - ntp
#   - ssl-keys

#- hosts: mysql
#  roles:
#   - mysql

- hosts: www
  roles:
   - ssl-keys

- hosts: bamboo
  roles: 
   - timezone
  vars:
   timezone: UTC

- hosts: docker
  roles:
    - docker
    - docker-compose

# TODO: make own roles for this
- hosts: dbreset
  tasks:
   - name: Insert dbreset scripts 
     synchronize: archive=no
                  dest=/opt/scripts/
                  mode=push
                  perms=yes
                  recursive=yes
                  src=../scripts/dbreset
