---
# Master Playbook

- hosts: all
  become: true
  tasks:
   - include: tasks/hostname.yml # should happen before installing datadog
   - include: tasks/updates.yml

- hosts: all
  become: true
  tags:
    - soe
  roles:
   - users
   - sudo
   - sshd
   - ufw
   - datadog
  tasks:
    - include: tasks/extra-monitoring.yml
  handlers:
    - include: handlers/monitoring.yml

- hosts: vagrant
  become: true
  tags:
    - vagrant
  roles:
    - logrotate

- hosts: tls
  tags:
    - tls
  become: true
  tasks:
    - include: tasks/extra-tls.yml
  roles:
    - dhparam
    - letsencrypt
  handlers:
    - include: handlers/monitoring.yml

- hosts: web
  become: true
  tags:
    - web
  roles:
   - nginx

- hosts: backup
  become: true
  tags:
   - backup
  tasks:
   - include: tasks/backup.yml
  roles:
   - aws-cli
  handlers:
    - include: handlers/monitoring.yml

- hosts: docker
  become: true
  tags:
   - docker
  roles:
   - docker
   - docker-compose
   - docker-compose-openmrs
  tasks:
   - include: tasks/docker-install-hacks.yml
  handlers:
    - include: handlers/monitoring.yml

- hosts: jira
  become: true
  pre_tasks:
    - include: tasks/install-openjdk.yml
  roles:
    - jira
    - mysql-connector-java
  tags:
    - jira

- hosts: confluence
  become: true
  pre_tasks:
    - include: tasks/install-openjdk.yml
  roles:
    - confluence
    - mysql-connector-java
  tags:
    - confluence

- hosts: bamboo
  become: true
  pre_tasks:
    - include: tasks/install-openjdk.yml
  roles:
    - bamboo
    - mysql-connector-java
    - logrotate
  tags:
    - bamboo

- hosts: bamboo-agent
  become: true
  tasks:
   - include: tasks/bamboo-agent.yml
  tags:
    - bamboo-agent

- hosts: crowd
  become: true
  pre_tasks:
    - include: tasks/install-openjdk.yml
  roles:
    - crowd
    - mysql-connector-java
  tags:
    - crowd

- hosts: mysql
  become: true
  tags:
    - mysql
  pre_tasks:
    - include: tasks/mysql-prepare-datadir.yml
  roles:
    - mysql
    - mysql-cron-backup

- hosts: discourse
  become: true
  roles:
    - { role: 'custom_roles/docker-discourse' }
