---
# Master Playbook
- hosts: all
  become: true
  roles:
   - users
   - sudo
   - sshd
   - ufw

#- hosts: mysql
#  roles:
#   - mysql

#- hosts: ssl
#  roles:
#   - ssl-keys
  #vars:
   #ssl_key_loc: ~/omrs-cert/

- hosts: web-tls
  become: true
  tasks:
    - name: add executable mode to deploy script wrapper
      file:
        state: 'directory'
        path: "/etc/nginx/ssl"
        mode: "0755"
    - stat: path=/etc/nginx/ssl/dhparam.pem
      register: dhparam_file
    - name: 'Improve Key Exchange'
      shell: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 4096
      when: dhparam_file.stat.exists == False
  roles:
    - letsencrypt

- hosts: web
  become: true
  roles:
   - nginx
  tasks:
   - hostname:
       name: "{{ inventory_hostname_short }}"
   - name: "Build hosts file"
     lineinfile:
       dest: /etc/hosts
       regexp: '^127\.0\.0\.1'
       line: "127.0.0.1 {{ inventory_hostname }} {{ inventory_hostname_short }} localhost"
       state: present

- hosts: datadog
  name: Datadog
  become: yes
  become_user: root
  roles:
    - datadog
  tasks:
    - name: Adding dd-agent to docker group
      user: name='dd-agent'
        groups='docker'
        append=yes


- hosts: bamboo
  roles:
   - timezone
  vars:
   timezone: UTC

- hosts: docker
  become: true
  roles:
   - docker
   - docker-compose
   - docker-compose-openmrs
  tasks:
   - include: docker-install-hacks.yml

# TODO: make own roles for this
- hosts: dbreset
  become: true
  tasks:
   - name: Insert dbreset scripts
     synchronize: archive=no
                  dest=/opt/scripts/
                  mode=push
                  perms=yes
                  recursive=yes
                  src=../scripts/dbreset


# TODO: make a role
- hosts: ldap
  become: true
  tasks:
    - name: Insert ldap backup
      copy:
        owner: root
        group: root
        mode: 0700
        src: ../scripts/ldap-backup.sh
        dest: /opt/scripts/ldap-backup.sh
      tags:
        - backup
